apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: suss
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: suss
  template:
    metadata:
      labels:
        app.kubernetes.io/name: suss
    spec:
      serviceAccountName: suss
      containers:
        - name: suss
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: r.world-direct.at/library/suss:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              host: localhost
              path: /healthz
              port: 9993
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              host: localhost
              path: /healthz
              port: 9993
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          ports:
          - containerPort: 9993
            name: http
            protocol: TCP

      hostNetwork: true

      # we tolerate everything by default to run on master nodes
      tolerations:
        - operator: Exists