name: Build Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-image:

    runs-on: ubuntu-latest
    name: build-image
    steps:

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.WD_HARBOR_REPOSITORY_NAME }}
          username: ${{ vars.WD_HARBOR_LIBRARY_USER }}
          password: ${{ secrets.WD_HARBOR_LIBRARY_PASSWORD }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.WD_HARBOR_REPOSITORY_NAME }}/suss
          tags: |
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and Push container images
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
