name: goreleaser

on:
  push:
    branches: [ "feature/goreleaser" ]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.5
          cache: true

      - name: run tests
        run:  go test ./...

      - id: goreleaser
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WD_HARBOR_REPOSITORY_NAME: ${{ vars.WD_HARBOR_REPOSITORY_NAME }}

      - name: set outputs from goreleaser
        run: |
          version=$(echo $MD | jq -r ".version")
          echo "version=$version" >> $GITHUB_OUTPUT
        env:
          MD: ${{steps.goreleaser.outputs.metadata}}

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.WD_HARBOR_REPOSITORY_NAME }}
          username: ${{ vars.WD_HARBOR_LIBRARY_USER }}
          password: ${{ secrets.WD_HARBOR_LIBRARY_PASSWORD }}
