name: test-gh-registry

on:
  push:
    branches: feature/github-packages

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      version: unknown # we be set by goreleaser
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.5
          cache: true

    #   - name: run tests
    #     run:  go test ./...


      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: goreleaser
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository_owner }}/suss

    #   - name: build and push chart
    #     run: |
    #       helm lint ./chart
    #       helm package chart/ --version ${{ env.version }} --destination=./dist
    #       helm push ./dist/suss-${{ env.version }}.tgz oci://${{ vars.WD_HARBOR_CHART_REPOSITORY_NAME }}
          